### ISSUE TITLE
Make filter menu work with HTTPS

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/style-guide#3]
@jrobson153 We should fix this to work with HTTPS as well as HTTP. 
https://github.com/funkhaus/style-guide/blob/master/woo-template/js/store.js#L77

```
    // rebuild URL
    var newHref = 'http://' + href.join('/');
```

Maybe using `wp_localize_script()` or perhaps inferring it from the HREF's in the links.

**Comment by johndigital** [comment]
This has been fixed with: https://github.com/funkhaus/style-guide/commit/642b6e753f4a45e083e48712b22395b564ea415a

URLs will now maintain whatever protocol they originally had. This will also work if there is no protocol in the URL (relative links.)
