### ISSUE TITLE
Remove nested function

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/style-guide#4]
I think doing something like this is bad:

https://github.com/funkhaus/style-guide/blob/master/woo-template/js/store-checkout.js#L44

```
    controlBillFields: function(){

        // function to set state of billing fields based on checkbox
        var toggleFields = function(){
```

I think from a performance point of view it's bad, and also seems to be a faux par (but I'm not certain - open for debate):
http://code.tutsplus.com/tutorials/stop-nesting-functions-but-not-all-of-them--net-22315

Maybe just doing a `storeCheckout.initControlBillFields()` and then that calls `storeCheckout.toggleFields()` is smarter.

**Comment by johndigital** [comment]
Yea, this is definitely not ideal. I was trying to avoid having multiple functions to just deal with one simple UI element, but there's no good way around it. 

I've now separated the toggleFields function out onto its own: https://github.com/funkhaus/style-guide/commit/642b6e753f4a45e083e48712b22395b564ea415a
